kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: busybox
    commands:
      - echo "Setting up the environment"

  - name: install_dependencies
    image: composer:latest
    commands:
      - cp .env.example .env
      - composer install
      - php artisan key:generate

  - name: start_services
    image: laravelsail/php80-composer:latest
    commands:
      - ./vendor/bin/sail up -d
      - sleep 20

  - name: run_migrations
    image: laravelsail/php80-composer:latest
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: your_database
      DB_USERNAME: your_username
      DB_PASSWORD: your_password
    commands:
      - ./vendor/bin/sail artisan migrate --force
      - ./vendor/bin/sail artisan scout:import

  - name: run_tests
    image: laravelsail/php80-composer:latest
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: your_database
      DB_USERNAME: your_username
      DB_PASSWORD: your_password
    commands:
      - ./vendor/bin/sail artisan test

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - 3306

  redis:
    image: redis:latest
    ports:
      - 6379

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 7700
    environment:
      MEILI_NO_ANALYTICS: "true"

volumes:
  - name: vendor
    temp: {}

trigger:
  event:
    - push
    - pull_request
  branch:
    - drone-pipeline
    - master
