kind: pipeline
type: docker
name: laravel-sail

steps:
  - name: setup
    image: laravelsail/php80-composer
    environment:
      APP_ENV: testing
    commands:
      - cp .env.example .env
      - composer install
      - php artisan key:generate

  - name: install-npm
    image: node:14
    commands:
      - npm install

  - name: run-migrations
    image: laravelsail/php80-composer
    environment:
      APP_ENV: testing
    commands:
      - ./vendor/bin/sail up -d
      - ./vendor/bin/sail artisan migrate --seed

  - name: run-tests
    image: laravelsail/php80-composer
    environment:
      APP_ENV: testing
    commands:
      - ./vendor/bin/sail up -d
      - ./vendor/bin/sail artisan scout:import
      - ./vendor/bin/sail artisan test

  - name: build-assets
    image: laravelsail/php80-composer
    commands:
      - ./vendor/bin/sail up -d
      - ./vendor/bin/sail npm install
      - ./vendor/bin/sail npm run production

  - name: start-application
    image: laravelsail/php80-composer
    commands:
      - ./vendor/bin/sail up -d
      - ./vendor/bin/sail npm run dev &

  - name: run-cypress-tests
    image: cypress/included:9.1.1
    commands:
      - npm install
      - ./node_modules/.bin/cypress run

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700

volumes:
  - name: cache
    temp: {}

trigger:
  branch:
    - master
    - develop
  event:
    - push
    - pull_request
