services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --cleanup --interval 300

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"   # Traefik HTTP port
      - "443:443"  # Traefik HTTPS port
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - reservationproject

  php:
    image: devblaze/reservationproject:latest
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html/public
    networks:
      - reservationproject
    expose:
      - "9000"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx config
      - .:/var/www/html  # Mount Laravel app here
    depends_on:
      - php
    networks:
      - reservationproject
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`192.168.4.63`)"  # Adjust for your IP/Domain
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: reservationprojectv2
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - reservationproject

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_ENV: production
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    networks:
      - reservationproject

volumes:
  mysql:
    driver: local
  meili_data:
    driver: local

networks:
  reservationproject:
    driver: bridge
