version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --cleanup --interval 300

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true" # Dashboard access
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"  # Serves site on HTTP on port 80
      - "--entrypoints.websecure.address=:443"  # Serves site on HTTPS, e.g. free SSL
    ports:
      - "8080:80"     # Expose port 80 for HTTP traffic
      - "8443:443"   # Expose port 443 for HTTPS traffic
      - "8008:8080" # Expose Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Provides Docker access to Traefik
    networks:
      - reservationproject

  php:
    image: devblaze/reservationproject:latest  # Updated image
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html/public # Host's public directory is mounted in the container
    networks:
      - reservationproject
    expose:
      - "9000"  # PHP-FPM listens on port 9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`192.168.4.63`)"  # Traefik router for local IP
      - "traefik.http.routers.laravel.entrypoints=web"
      - "traefik.http.services.laravel.loadbalancer.server.port=9000"  # FastCGI port

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: reservationprojectv2
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - reservationproject

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_ENV: production
    ports:
      - "7700:7700"
    volumes:
      - meilisearch:/meili_data
    networks:
      - reservationproject

networks:
  reservationproject:
    driver: bridge

volumes:
  mysql:
    driver: local
  meilisearch:
    driver: local
