version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --cleanup --interval 300

  php:
    image: devblaze/reservationproject:latest
    volumes:
      - .:/var/www/html
      - ./.env.production:/var/www/html/.env
    networks:
      - reservationproject
    expose:
      - "9000"
    depends_on:
      - mysql
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_KEY=${MEILISEARCH_KEY}
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html
    depends_on:
      - php
    networks:
      - reservationproject
    ports:
      - "80:80"

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - reservationproject
    healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_ENV: production
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    networks:
      - reservationproject

volumes:
  mysql:
    driver: local
  meili_data:
    driver: local

networks:
  reservationproject:
    driver: bridge
