version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    command: --cleanup --interval 300

  php:
    #    image: devblaze/reservationproject:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - reservationproject
    expose:
      - "9000"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx config
      - .:/var/www/html  # Mount Laravel app here
    depends_on:
      - php
    ports:
      - "80:80"  # Directly expose port 80
    networks:
      - reservationproject

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: reservationprojectv2
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - reservationproject

  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      MEILI_ENV: production
      MEILI_MASTER_KEY: e0ibi2csFnnnRZtwLvjDGQBZtgaiDCYrudz6P1YEmCw
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    networks:
      - reservationproject

volumes:
  mysql:
    driver: local
  meili_data:
    driver: local

networks:
  reservationproject:
    driver: bridge
