name: CI for Laravel Sail Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest     # Use the latest version of Ubuntu for the build

    services:
      mysql:                    # A MySQL service required for Laravel Sail
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: reservationprojectv2
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3

      - name: Set up PHP 8.1                    # Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, bcmath, pdo_mysql, simplexml
          ini-values: post_max_size=256M, max_input_vars=5000
          coverage: none

      - name: Set up Node.js 16.x                # Setup Node.js for npm
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Setup environment and application key
        run: |
          cp .env.example .env             # Set the environment variable file
          php artisan key:generate      # Generate application key

      - name: Setup Docker Compose and Start Services
        run: |
          docker compose up -d   # Start docker containers

      - name: Install NPM dependencies
        run: |
          npm install
          npm run dev   # Build the frontend assets

      - name: Run database migrations and seeders
        run: |
          php artisan migrate --seed

      - name: Index the Models with Laravel Scout
        run: |
          php artisan scout:import "App\\Models\\Event"

      - name: Run Test Suite (PHPUnit/Dusk)
        run: |
          php artisan test

      - name: Lint and Fix CSS Files
        run: |
          npm run lint

      - name: Stop and Cleanup Services
        run: |
          docker compose down  # Stop Docker containers
